FROM maven:3.9.6-eclipse-temurin-17 AS ejb-builder

WORKDIR /app/ejb-module
COPY ejb-module/pom.xml .
COPY ejb-module/src ./src
RUN mvn clean package -DskipTests

FROM maven:3.9.6-eclipse-temurin-17 AS backend-builder

WORKDIR /app

COPY --from=ejb-builder /app/ejb-module/target/ejb-module-0.0.1-SNAPSHOT.jar ./ejb-module.jar

RUN mvn install:install-file \
    -Dfile=/app/ejb-module.jar \
    -DgroupId=com.example \
    -DartifactId=ejb-module \
    -Dversion=0.0.1-SNAPSHOT \
    -Dpackaging=jar

COPY backend-module/pom.xml ./backend-module/pom.xml

COPY backend-module/src ./backend-module/src

WORKDIR /app/backend-module
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

RUN apk add --no-cache wget

COPY --from=backend-builder /app/backend-module/target/*.jar app.jar

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/api-docs || exit 1

ENTRYPOINT ["java", "-jar", "app.jar"]

